//BASEURL=http://localhost:3333
// GET Request to home route
GET http://localhost:3333

###

//login route
GET http://localhost:3333/users/login/
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

//new user route
POST http://localhost:3333/users/
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

//delete user route
DELETE http://localhost:3333/users/
Content-Type: application/json

{
    "authkey": "4c5fb08b-021d-4eab-b8c2-1764f05cf870" 
}

###

//edit user route
PUT http://localhost:3333/users/
Content-Type: application/json

{
    "authkey" : "6370e748-1731-4b7c-87c8-380fd462b4d5",
    "username": "Jake234",
    "password": "idk233"
}